const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.EightDir,
		C3.Plugins.Touch,
		C3.Behaviors.Bullet,
		C3.Behaviors.Orbit,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Orbit.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsTagPlaying
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{basePad: 0},
	{stickPad: 0},
	{Sine: 0},
	{"8Direction": 0},
	{player: 0},
	{Touch: 0},
	{desk: 0},
	{tavolo: 0},
	{Sprite: 0},
	{Bullet: 0},
	{figure: 0},
	{f: 0},
	{Orbit: 0},
	{nPunti: 0},
	{titolo: 0},
	{punti: 0},
	{topScore: 0},
	{nTopPunti: 0},
	{LocalStorage: 0},
	{pausa: 0},
	{sfondo: 0},
	{help: 0},
	{scrittaHelp: 0},
	{tutorial: 0},
	{Audio: 0},
	{suono: 0},
	{crezioneNemici: 0},
	{movimeno: 0},
	{collisione: 0},
	{animazioniPlay: 0},
	{difficolta: 0},
	{topPunti: 0}
];

self.InstanceType = {
	basePad: class extends self.ISpriteInstance {},
	stickPad: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	desk: class extends self.ISpriteInstance {},
	tavolo: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	figure: class extends self.ISpriteInstance {},
	f: class extends self.ISpriteInstance {},
	nPunti: class extends self.ITextInstance {},
	titolo: class extends self.ISpriteInstance {},
	punti: class extends self.ISpriteInstance {},
	topScore: class extends self.ISpriteInstance {},
	nTopPunti: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	pausa: class extends self.ISpriteInstance {},
	sfondo: class extends self.ISpriteInstance {},
	help: class extends self.ISpriteInstance {},
	scrittaHelp: class extends self.ITextInstance {},
	tutorial: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	suono: class extends self.ISpriteInstance {}
}